on:
  push:
    branches: [main, preview, "preview-*"]
  pull_request:
    branches: [main, preview, "preview-*"]
    types: [opened, synchronize, reopened, ready_for_review]

name: Run Unit/Feature Tests

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'workflow_run' ||
      (
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'pull_request'
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.sha }}

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies # (assuming your project has dependencies)
        run: bun install # You can use npm/yarn/pnpm instead if you prefer

      - name: Run tests
        run: bun test